---
name: Docker build

# yamllint disable-line rule:truthy
on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        uses: actions/checkout@v4.2.2
      -
        name: Shortcut Version Code
        id: version
        run: echo ::set-output name=version::$(jq -r '."."' .github/release-please-manifest.json)
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        if: github.ref_name == github.event.repository.default_branch
        name: Build and push on default branch
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: bazelbuild:latest,bazelbuild:${{ github.sha }},bazelbuild:${{ steps.version.outputs.version }}
      -
        if: github.ref_name != github.event.repository.default_branch
        name: Build only not on default branch
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: false
          tags: bazelbuild:latest,bazelbuild:${{ github.sha }},bazelbuild:${{ steps.version.outputs.version }}
